### ISSUE TITLE
Error when I run unit test bash file

### ISSUE THREAD

**Issue by rickyvargas** [ayllu/aynipy#42]
ImportError: Failed to import test module: test_user_entity
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/rickyvargas/Documents/GITHUB/aynipy/Tests/UnitTest/test_user_entity.py", line 2, in <module>
    from pyvaru import ValidationException
ImportError: No module named pyvaru

**Comment by gcvalderrama** [comment]
Please check your python version (:
