### ISSUE TITLE
Quipu event error

### ISSUE THREAD

**Issue by poluz86** [ayllu/aynipy#46]
An error occurred when a quipu is trying to be processed

=================EXCEPTION=====================
[2017-09-27 14:02:08,213] 
ERROR in agenthost: 'list' object has no attribute 'items'
****************STACK**************************

Traceback (most recent call last):
  File "agenthost.py", line 52, in process_quipu
    quipu_service.process_quipu()
  File "F:\Gamification\aynipy\Ayni\Services\QuipuService.py", line 71, in process_quipu
    quipu_entity.process()
  File "F:\Gamification\aynipy\Ayni\Core\QuipuEntity.py", line 51, in process
    score = self.__process_score()
  File "F:\Gamification\aynipy\Ayni\Core\QuipuEntity.py", line 39, in __process_score
    script = self.generate_script()
  File "F:\Gamification\aynipy\Ayni\Core\QuipuEntity.py", line 30, in generate_script
    for key, value in self.data.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by gcvalderrama** [comment]
load from a database error

**Comment by poluz86** [comment]
Still Happening

=================EXCEPTION=====================
[2017-09-28 11:02:08,898] 
ERROR in agenthost: 'list' object has no attribute 'items'
****************STACK**************************

Traceback (most recent call last):
  File "agenthost.py", line 53, in process_quipu
    quipu_service.process_quipu()
  File "F:\gamification\aynipy\Ayni\Services\QuipuService.py", line 75, in process_quipu
    quipu_entity.process()
  File "F:\gamification\aynipy\Ayni\Core\QuipuEntity.py", line 61, in process
    score = self.__process_score()
  File "F:\gamification\aynipy\Ayni\Core\QuipuEntity.py", line 46, in __process_score
    self.generate_script()
  File "F:\gamification\aynipy\Ayni\Core\QuipuEntity.py", line 37, in generate_script
    for key, value in self.data.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by gcvalderrama** [comment]
The issue was related to the content of data column that was a list and not a dictionary now we are validating the data type also
